name: build

# トリガー
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    name: build
    steps:
    - uses: actions/checkout@v2    
    - name: build
      run: |
        docker build --build-arg USER_EMAIL=${{ secrets.USER_EMAIL }} --build-arg USER_NAME=${{ secrets.USER_NAME }} -t lineage17 .
